name: Build and Notify
on:
  pull_request:
    types: [opened,closed]
  issues:
    types: [opened, closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Notify
      uses: athul/SGS@master
      if: always()
      with:
        FROM_NUM: ${{ secrets.FROM_NUM }}
        TO_NUM: ${{ secrets.TO_NUM }}
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
