name: Build and Notify
on:
  pull_request:
    types: [opened,closed]
  issues:
    types: [opened, closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Notify
      uses: athul/SGS@master
      if: always()
      with:
        from_num:${{ secrets.FROM }}
        to_num:${{ secrets.TO }}
        TWILIO_ACCOUNT_SID:${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY:${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET:${{ secret.TWILIO_API_SECRET }}
